version: "2"
services:
  app:
    build: .
    container_name: fmu
  node:
    image: "node:8"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"    